language: r

matrix:
    include:
  #      - os: linux
  #        r: oldrel
        - os: linux
          r: release
  #      - os: linux
  #        r: devel
  #      - os: osx
  #        r: oldrel
  #      - os: osx
  #        r: release
    
    
sudo: false

dist: trusty

cache: packages

latex: true

r_github_packages:
  - r-lib/pkgdown
  
r_packages:
  - covr
     
after_success:
  - Rscript -e 'pkgdown::build_site()'
  - Rscript -e 'library(covr); codecov()'
      
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: docs
  on:
    branch: master

notifications:
  slack:
    rooms:
      - secure: "RZqAAMBvmp4mXkll+RqWXsl26MLeEpAn/9reH0cTtMabj7NJu7gD8/hgOQGAMPuYW3OQzlO6K9NG66LV7J9opudGbimXpgmH1qUqyci+uGu2agX1lGAo+VmfvA2jeKZl5EutEMUdyv2Q9Nmmo0/2XUoHc5cryQNSonCwtH5tYpyT0jKNDJtHuYTR5lVu+Lqa8KxX7a+fA7jrDLf6Qrym30Sa1m/FqD36qmRETftfd+IWxikUW+wNu0T5gi6kUuMSqnqugM8EtEDcP57EJRj+8jfCqjECbhrpisx2jQ9o/hQgF0W/CdTIwl3HASD/2uGh2rMe4iQDfcloer6tCFVuQD51kgKxzsZD2bbYpqfDnDafNBONu6Ya05vCGUSXKpZNTWy4Cet6tVZixYE3V4pRuTXBLj4bh6Mw6B9hIanMUYSCiWTclxGBTL1b7aRR2kZou5CQd0cT+U2AYU4afkzRVz5aN/Aa8+BkENg+cqAMhT1/SdJeOgplyu5JDYCaxeR/pl3gaMbUkoyH2NxDGx/QwH71I8M8W8kYqIv/2ugYcsmJDE2uLEMLNviKhseN8W1bfiOeVHXTPMHlZxpdNqwxa7rWkiVYrtdg2Auyy/JSH9p1JLEu9cn5wxDYGntgpdGT8FS4wDTsN1d8khx5tKJgSMAIlps7+AzPjjgSZNlHkgk="
    on_success: always
    on_failure: always
    on_pull_requests: false
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"
  email: false
