language: r

os:
 - linux

dist: xenial

cache: packages

latex: true

r_github_packages:
  - r-lib/pkgdown
  
r_packages:
  - covr
     
after_success:
  - Rscript -e 'devtools::install()'
  - Rscript -e 'pkgdown::build_site()'
  - Rscript -e 'library(covr); codecov()'
      
deploy:
  provider: pages
  token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: false
  local_dir: docs
  on:
    branch: master
